### ISSUE TITLE
Bug: 500 error - cross-fetch not supported

### ISSUE THREAD

**Issue by dodanex** [YsarocK/nuxt-appwrite#21]
**Describe the bug**
After a fresh install of Nuxt 3 with only this module, there is this error regarding `cross-fetch` that's preventing the app to start.

**To Reproduce**
1. Fresh install a new Nuxt 3 app
2. Install and add the `nuxt3-appwrite` module
3. Create an `.env` file and add the required appwrite fields
4. Edit the `nuxt.config.ts` as follows:

```js
export default defineNuxtConfig({
	runtimeConfig: {
		APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT,
		APPWRITE_PROJECT_ID: process.env.APPWRITE_PROJECT_ID
	},

	modules: ['nuxt3-appwrite'],

	appwrite: {
		proxyRoute: '/appwrite' // Default to /appwrite
	}
})
```
5. Run the nuxt app and test it in the browser

**Expected behavior**
The webpage should work, but instead there is this error:

```
500
require() of ES Module D:\www\test\nuxt3-appwrite\node_modules\node-fetch\src\index.js from D:\www\test\nuxt3-appwrite\cross-fetch not supported. Instead change the require of index.js in D:\www\test\nuxt3-appwrite\cross-fetch to a dynamic import() which is available in all CommonJS modules.
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version 112.0.1722.48 (Official build) (64-bit)

**Comment by YsarocK** [comment]
Hello,

Thanks for your issue. First time I get it & have some ideas about the origin. 

I check it tomorrow, sorry for the inconvenience 😅

**Comment by YsarocK** [comment]
@dodanex May I ask you the version of node you're using ?
