### ISSUE TITLE
No typescript types

### ISSUE THREAD

**Issue by mariusbolik** [YsarocK/nuxt-appwrite#63]
**Describe the bug**
I don't have typescript types after installing the library.

**Expected behavior**
Types should be visible when hovering an entity, like in the official sdk.

**Screenshots**
<img width="351" alt="Bildschirmfoto 2023-07-21 um 16 01 40" src="https://github.com/YsarocK/nuxt-appwrite/assets/39862171/448a62a8-9ecf-44b7-8c2b-ce4e2ad7142d">

**Comment by mariusbolik** [comment]
Hello @YsarocK,

I added you to the repo. I would appreciate it if you take a look.
Code is in /pages/_appwrite.vue

Kind Regards,
Marius

**Comment by YsarocK** [comment]
Thanks a lot !
Will look at it tomorrow if you don't see any issue.

**Comment by mariusbolik** [comment]
Thank you. The useAppwrite.d.ts declares it as any:
```ts
/**
 * Use the current Appwrite instance
 * @returns Client, Databases, Account, Storage, Avatars, Functions, Role, Permission
 */
declare const useAppwrite: () => any;
export default useAppwrite;

```
