### ISSUE TITLE
[documentation] add `how to contribute` section to README

### ISSUE THREAD

**Issue by FranciscoKloganB** [YsarocK/nuxt-appwrite#79]
**As a** consumer of `nuxt3-appwrite`
**I want** to be able to contribute to it spontanously
**So that** the project may grow organically

Having an `How to Contribute` guide on the GitHub readme section is of the utmost important for OSS projects to survive and avoid premature deaths.

Something as simple as this might be enough (taken from nuxt/image) repository.

```
## Contributing

- Clone this repository
- Enable [Corepack](https://github.com/nodejs/corepack) using corepack enable
- Install dependencies using pnpm install
- Run pnpm dev:prepare to generate type stubs.
- Use pnpm dev to start [playground](https://github.com/nuxt/image/blob/main/playground) in development mode.
```

**Comment by YsarocK** [comment]
Hi Francisco!

Thanks for your message.

You're right, it's missing. Will add it tonight!

Have a good day, I wait for your PRs 😇
