### ISSUE TITLE
The requested module does not provide an export named 'Account'

### ISSUE THREAD

**Issue by mariusbolik** [YsarocK/nuxt-appwrite#98]
**Describe the bug**
My PWA shows a blank white page. In the console I see the following error:
```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/node-appwrite/index.js?v=4149e115' does not provide an export named 'Account'
```

**To Reproduce**
I added the Vuefire Module like here: https://vuefire.vuejs.org/nuxt/getting-started.html
After that, the error occoured. I don't know exactly why Vuefire reveals this error, but could you check if the exports are correct?

**Expected behavior**
Exports should be available. And is there a way to not use `node-appwrite` if `ssr` is set to `false` in config?

**Screenshots**
<img width="917" alt="Bildschirmfoto 2023-11-22 um 15 01 42" src="https://github.com/YsarocK/nuxt-appwrite/assets/39862171/6d5bda7c-f1c8-430b-8a8a-485fe54fc30c">
<img width="998" alt="Bildschirmfoto 2023-11-22 um 15 05 18" src="https://github.com/YsarocK/nuxt-appwrite/assets/39862171/19d1ffe9-70f2-4c44-a219-0c9cb7aacaf9">

**Comment by YsarocK** [comment]
Hey.

Thanks for the issue, added to my todo, expect to be done before this Friday.

Have a nice day!
